# Generated by Django 3.2.8 on 2021-10-16 06:41

from django.db import migrations, models

import shortener.validators

class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [

        migrations.CreateModel(

            name='Kirurl',

            fields=[

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('url', models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com])),

                ('shortcode', models.CharField(blank=True, max_length=13, unique=True)),

                ('updated', models.DateTimeField(auto_now=True)),

                ('mtime', models.DateTimeField(auto_now_add=True)),

                ('active', models.BooleanField(default=True)),

            ],

        ),

    ]


